### ISSUE TITLE
Find ranges for 'successful' constants

### ISSUE THREAD

**Issue by jannesschmitz** [frederik-lange/pxd_teststand_software#8]
Compare calibration constants for all PSs (database) and find ranges for successful calibrations.
This is needed as input for the automatic pass/fail.

From the analysis of standard parameter variation between different PSs and channels you should get some nice plots to explain how you determined the constant ranges.
It might be beneficial to group certain channel that behave the same (e.g. ccg1/2/3) to increase statistics.

Document the decision for calibration ranges and underlying thoughts!

**Comment by frederik-lange** [comment]
Calculate theoretical calibration constants (via Documentation)

**Comment by BothoP** [comment]
@frederik-lange Where is the documentation you mention here? It is a good idea to include links to e.g. confluence or code (github/gitlab/branches) in the ticket for future reference. 
Comments to your determination of the range and the corresponding histograms:

- Please make sure to properly disentangle two things
  - Histogram for the full range: should only include a single entry per PS, not multiple
  - Histogram for "singe unit calibration variation": here you can histogram the values of a single unit, that would be interesting too, then you can compare the 'full parameter variation' between PS and the variation you get from calibration to calibration because of other factors like environment change, measurement uncertainties, fit uncertainties...
- For your overview histogram for the variations of all channels maybe box plots might be nice, like here
![image](https://user-images.githubusercontent.com/13351658/217547130-bb7814c7-31c7-403b-ae99-ec5728356ef4.png)
how to do: https://matplotlib.org/stable/gallery/statistics/boxplot_demo.html#sphx-glr-gallery-statistics-boxplot-demo-py
